name: CI and Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup_environment:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.node-version.outputs.version }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        id: node-version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

  test_application:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Execute Tests
        run: npm test

  build_and_analyze:
    name: Build and Code Quality Analysis
    runs-on: ubuntu-latest
    needs: setup_environment
    environment: Test

    steps:
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
